openapi: 3.0.0
info:
  title: Recipes
  version: '1.0'
  description: >-
    <span style="font-size: 3em; color: #5D535E;">
      <i class="fas fa-paper-plane fa-2x"></i> <i>Rosa</i></span> 

    </br>

    </br>


    Interact with the `'Recipes'` API to get a list of recipes, add
    or remove recipes, and to update existing recipes.


    Use this API to leverage Rosa's central repository of recipes that
    allow's users to make menus and grocery lists.



    ```bash

    curl --request GET \
      --url 'https://rosa.philliplehner.com/api/recipes/abc?spaceid=all&sort=desc&limit=10' \
      --header 'apikey: 123' \
      --header 'deviceid: all'
    ```


  contact:
    name: Phillip Lehner
    email: pl@philliplehner.com
    url: philliplehner.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://rosa.philliplehner.com/v1'
paths:
  '/recipes/{recipeID}':
    parameters:
      - schema:
          type: integer
        name: recipeID
        in: path
        required: true
        description: Id of an existing recipe.
    get:
      summary: Get Recipe Info by Recipe ID
      tags: []
      responses:
        '200':
          description: Recipe Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
              examples:
                Get Recipe Biscuits:
                  value:
                    id: 142
                    title: 'Biscuits'
                    servings: '12'
        '404':
          description: Recipe Not Found
      operationId: get-recipes-recipeId
      description: Retrieve the information of the recipe with the matching recipe ID.
    patch:
      summary: Update Recipe Information
      operationId: patch-recipes-recipeId
      responses:
        '200':
          description: Recipe Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
              examples:
                Updated Recipe Biscuits:
                  value:
                    id: 142
                    title: Buttermilk Biscuits
                    servings: '13'
        '404':
          description: Recipe Not Found
        '409':
          description: Title Already Taken
      description: Update the information of an existing recipe.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                servings:
                  type: string
            examples:
              Update Title:
                value:
                  title: Buttermilk Biscuit Bites
              Update Servings:
                value:
                  servings: '13'
        description: Patch recipe properties to update.
  '/recipe':
    post:
      summary: Create New Recipe
      operationId: post-recipe
      responses:
        '200':
          description: Recipe Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
              examples:
                New Recipe Baked Beans:
                  value:
                    id: 12
                    title: 'Baked Beans'
                    servings: '8'
        '400':
          description: Missing Required Information
        '409':
          description: Title Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                servings:
                  type: string
              required:
                - title
                - servings
            examples:
              Create Recipe Smores:
                value:
                  title: 'Smores'
                  servings: '10'
        description: Post the necessary fields for the API to create a new recipe.
      description: Create a new recipe.
components:
  schemas:
    Recipe:
      title: Recipe
      type: object
      description: ''
      x-examples:
        Biscuit:
          id: 142
          title: Buttermilk Biscuit
          servings: '12'
      properties:
        id:
          type: integer
          description: Unique identifier for the given recipe.
        title:
          type: string
        servings:
          type: string
      required:
        - id
        - title
        - servings
